### ISSUE TITLE
Function comments are using future tense 😱

### ISSUE THREAD

**Issue by Ullaakut** [jlevesy/go-sind#11]
`// DockerHost will return the host to use to communicate with the swarm cluster.`
`// ContainerList will return the lists of containers.`
`// ValidateName will return true if a cluster already have this name.`
`// Save will persist a new cluster.`
`// Delete will delete the cluster` <- This one is also missing a dot!

Also, in the README:

```
# Will create a new cluster with 3 managers, 3 workers  and the port 8080 of the host bound
# to the port 8080 of the ingress network of the cluster.
sind create --managers=3 --workers=3 -p 8080:8080
```

**Comment by jlevesy** [comment]
Closed by #17
