### ISSUE TITLE
Sind logo.

### ISSUE THREAD

**Issue by jlevesy** [jlevesy/go-sind#13]
We need a Logo.

@Ullaakut, GO !

**Comment by Ullaakut** [comment]
![happy](https://user-images.githubusercontent.com/6976628/54270450-bfa5fb80-457f-11e9-8f5c-8db530254cf1.gif)

**Comment by Ullaakut** [comment]
(Please assign me to this! :D)

**Comment by Ullaakut** [comment]
Whoops 😁
