### ISSUE TITLE
Add a "--force" option to sind delete

### ISSUE THREAD

**Issue by dduportal** [jlevesy/go-sind#38]
I ran (multiple times) on a situation where the containers hosting my sind clusters are gone (aka. `docker ps` reports no container running), 

but `sind list` reports a cluster (because the file `${HOME}/.config/sind/clusters.json` still refers to the clusters).

If I try to delete the cluster, then I run into an error, and the `clusters.json` file is not updated (and also, a endline is missing at the end of the output ;) ):

```shell
sind delete --cluster=dockeree
Deleting cluster "dockeree"...
unable to tear down cluster: unable to delete cluster network: network not foundHackintosh-de-Dadou:traefikee-demo-dockeree dadou$
```

Proposal: 

- Introduce a `--force` flag/option to the command `sind delete`, which will continue deletion even though if issues are thrown by the Docker API (no network/volume/container/any Docker object found), and proceed to updating the `clusters.json`
- When the flag `--force` is not used (in the example provided earlier), then a nice message should tell the user: "An error occured while trying to delete the cluster named xxxx. If you really want to get rid of the cluster, then use "sind delete --force --cluster=xxx".

**Comment by jlevesy** [comment]
Closed by #43
