### ISSUE TITLE
Sind env should unset DOCKER_CERT_PATH

### ISSUE THREAD

**Issue by Ullaakut** [jlevesy/go-sind#42]
`sind env` should unset the `DOCKER_CERT_PATH` if specified, otherwise the cluster won't be accessible after running `eval (sind env)`.

**Comment by Ullaakut** [comment]
Nevermind, just realized it can be set in the environment using `DOCKER_CERT_PATH` and naming the files appropriately 🤦‍♂

**Comment by jlevesy** [comment]
To do that, we would need to support various shells, like fish :fish: .
